name: Register Component
description: Registers a Component
inputs:
  tenant-id:
    description: 'Tenant id'
    required: true
  subscription-id:
    description: 'Azure subscription id'
    required: true
  resource-group:
    description: 'Azure resource group'
    required: true
  workspace-name:
    description: 'Azure Machine Learning workspace name'
    required: true
  client-id:
    description: 'Client id configured with Federated Credentials'
    required: true
  component-name:
    description: 'Component name'
    required: true
  component-path:
    description: 'Component-path'
    required: true
  component-version:
    description: 'Component version'
    required: false

outputs:
  component-id:
    description: 'resource id of the component'
    value: "from below"

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: true
        auth-type: SERVICE_PRINCIPAL

    - name: Register Component
      shell: bash
      id: register_component
      run: |
        az extension add -n ml -y
        echo "component-id=$(\
        az ml component create --query id \
        --file ${{ inputs.component-path }}/component.yml \
        -n ${{ inputs.component-name }} \
        -g ${{ inputs.resource-group }} \
        -w ${{ inputs.workspace-name }} \
        --subscription ${{ inputs.subscription-id }} \
        --query "join(':',['azureml',name,version])" \
        --output tsv \
        )" \
        >> "$GITHUB_OUTPUT"
    - name: Get Result
      shell: bash
      run: |
        echo "Reference to AzureML Component: ${{ steps.register_component.outputs.component-id }}"