name: hello

inputs:
  name:
    description: 'name to greet'
    required: true
    default: 'World'

runs:
  using: "composite"
  steps:
    - name: Hi
      run: |
        echo "Hello! ${{ inputs.name }}"

